
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class GameWindow extends javax.swing.JPanel {

    /**
     * Creates new form GameWindow
     */
    
    Image menuImage;
    Image sunflowerImage;
    ArrayList<Plant> listPlant = new ArrayList<>();
    ArrayList<Plant> plantDitanam = new ArrayList<>();
    Plant selectedPlant = null;

    public GameWindow() {
        initComponents();
        this.setSize(1000, 752);
        
        try {
            menuImage = ImageIO.read(new File("images/mainBG.png"));
        } catch (IOException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try { 
            sunflowerImage = ImageIO.read(new File("images/sunflower.gif"));
            listPlant.add(new Sunflower(5, 0, 100, sunflowerImage, 160, 610));
        } catch (IOException ex) {
            System.out.println("Gambar Sunflower tidak ada");
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        g.clearRect(0, 0, 1000, 752);
        g.drawImage(menuImage, 0, 0, 1000, 752, null);
        for(Plant i : plantDitanam) {
            i.draw(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1000, 752));
        setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
