
import java.awt.Image;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alvin
 */
public class ShowUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowUserFrame
     */
    Image menuImage =null;
    public static int select=0;
    public static int temp=0;
    public static Scanner sc = new Scanner(System.in);
    public ShowUserFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(1004, 745);
        Del_Btn.setContentAreaFilled(false);
        Del_Btn.setBorderPainted(false);
        Ok_Btn.setContentAreaFilled(false);
        Ok_Btn.setBorderPainted(false);
        Can_Btn.setContentAreaFilled(false);
        Can_Btn.setBorderPainted(false);
        New_Btn.setContentAreaFilled(false);
        New_Btn.setBorderPainted(false);
        
        try{
            user1.setText(Driver.player.get(0).getUsername());
        }catch(Exception e){
            user1.setText("-");
        }
        
        try{
            user2.setText(Driver.player.get(1).getUsername());
        }catch(Exception e){
            user2.setText("-");
        }
        
        try{
            user3.setText(Driver.player.get(2).getUsername());
        }catch(Exception e){
            user3.setText("-");
        }
        
        try{
            user4.setText(Driver.player.get(3).getUsername());
        }catch(Exception e){
            user4.setText("-");
        }
        
        try{
            user5.setText(Driver.player.get(4).getUsername());
        }catch(Exception e){
            user5.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showUserPanel1 = new ShowUserPanel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        Del_Btn = new javax.swing.JButton();
        Can_Btn = new javax.swing.JButton();
        New_Btn = new javax.swing.JButton();
        Ok_Btn = new javax.swing.JButton();
        user2 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(811, 607));

        showUserPanel1.setPreferredSize(new java.awt.Dimension(1004, 745));

        user4.setBackground(new java.awt.Color(255, 255, 255));
        user4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user4.setForeground(new java.awt.Color(255, 255, 255));
        user4.setText(Driver.player.get(0).getUsername());
        user4.setToolTipText("");
        user4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        user4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user4MouseClicked(evt);
            }
        });

        user5.setBackground(new java.awt.Color(255, 255, 255));
        user5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user5.setForeground(new java.awt.Color(255, 255, 255));
        user5.setText(Driver.player.get(0).getUsername());
        user5.setToolTipText("");
        user5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        user5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user5MouseClicked(evt);
            }
        });

        Del_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Del_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Del_BtnMouseClicked(evt);
            }
        });

        Can_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Can_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Can_BtnMouseClicked(evt);
            }
        });

        New_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        New_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_BtnMouseClicked(evt);
            }
        });

        Ok_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ok_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ok_BtnMouseClicked(evt);
            }
        });

        user2.setBackground(new java.awt.Color(255, 255, 255));
        user2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setText(Driver.player.get(0).getUsername());
        user2.setToolTipText("");
        user2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user2MouseClicked(evt);
            }
        });

        user1.setBackground(new java.awt.Color(255, 255, 255));
        user1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setText(Driver.player.get(0).getUsername());
        user1.setToolTipText("");
        user1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });

        user3.setBackground(new java.awt.Color(255, 255, 255));
        user3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user3.setForeground(new java.awt.Color(255, 255, 255));
        user3.setText(Driver.player.get(0).getUsername());
        user3.setToolTipText("");
        user3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        user3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showUserPanel1Layout = new javax.swing.GroupLayout(showUserPanel1);
        showUserPanel1.setLayout(showUserPanel1Layout);
        showUserPanel1Layout.setHorizontalGroup(
            showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showUserPanel1Layout.createSequentialGroup()
                .addGroup(showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showUserPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(showUserPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ok_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(New_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Can_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(Del_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        showUserPanel1Layout.setVerticalGroup(
            showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showUserPanel1Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(showUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(showUserPanel1Layout.createSequentialGroup()
                        .addComponent(Del_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Can_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(showUserPanel1Layout.createSequentialGroup()
                        .addComponent(New_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Ok_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(showUserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(showUserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4MouseClicked
        temp=3;
        select=3;
    }//GEN-LAST:event_user4MouseClicked

    private void user5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5MouseClicked
        temp=4;
        select=4;
    }//GEN-LAST:event_user5MouseClicked

    private void Del_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Del_BtnMouseClicked
        if (Driver.player.size()==1) {
            try {
                Driver.player.remove(temp);
                RegisterAccountFrame RAF = new RegisterAccountFrame();
                RAF.setVisible(true);
                RAF.setLocationRelativeTo(null);
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Tidak ada data yang di select!", "Warning!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            try {
                Driver.player.remove(temp);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Tidak ada data yang di select!", "Warning!", JOptionPane.ERROR_MESSAGE);
            }
            MainMenuFrame MM = new MainMenuFrame();
            MM.setVisible(true);
            MM.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Del_BtnMouseClicked

    private void Can_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Can_BtnMouseClicked
        MainMenuFrame MM = new MainMenuFrame();
        MM.setVisible(true);
        MM.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_Can_BtnMouseClicked

    private void New_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_BtnMouseClicked
        if (Driver.player.size()<5) {
            RegisterAccountFrame RAF = new RegisterAccountFrame();
            RAF.setVisible(true);
            RAF.setLocationRelativeTo(null);
            this.setVisible(false);
        }else
        JOptionPane.showMessageDialog(this, "Data user telah penuh!", "Warning!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_New_BtnMouseClicked

    private void Ok_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ok_BtnMouseClicked
        CheckPassword CP = new CheckPassword();
        CP.setVisible(true);
        CP.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_Ok_BtnMouseClicked

    private void user2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseClicked
        temp=1;
        select=1;
    }//GEN-LAST:event_user2MouseClicked

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked
        temp=0;
        select=0;
    }//GEN-LAST:event_user1MouseClicked

    private void user3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseClicked
        temp=2;
        select=2;
    }//GEN-LAST:event_user3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Can_Btn;
    private javax.swing.JButton Del_Btn;
    private javax.swing.JButton New_Btn;
    private javax.swing.JButton Ok_Btn;
    private ShowUserPanel showUserPanel1;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    // End of variables declaration//GEN-END:variables
}
